name: hello world workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: hello world 2
              run: echo "Hello World 2"
              shell: bash
              
    goodbye:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: goodbye world 2
              run: echo "Goodbye world 2"
              shell: bash
